server:
  port: 9000

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/se2005?useSSL=false
    username: root
    password: 110720woaini

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://127.0.0.1:8100/eureka/  
  
mybatis: 
  mapper-locations: 
  - classpath:mapper/*Mapper.xml 
